### ISSUE TITLE
Use EPIC-maintained hpc-stacks on RDHPCS

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/GSI-utils#13]
The current hpc-stack installs are frozen. Management of hpc-stack installs on the RDHPCS platforms has moved to EPIC. Update GSI-utils to use the EPIC-installed hpc-stacks on Hera, Orion, and Jet.

Matching global-workflow issue https://github.com/NOAA-EMC/global-workflow/issues/1311

**Comment by DavidHuber-NOAA** [comment]
@KateFriedman-NOAA I think this can be closed in favor or #18.

**Comment by KateFriedman-NOAA** [comment]
Agreed @DavidHuber-NOAA . Closing.
