### ISSUE TITLE
interp_inc/HDF5

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [NOAA-EMC/GSI-utils#14]
The interp_inc executable currently does not work with hdf5 past version 1.10.8. This is because later versions of hdf5 for certain routines require that the MPI root process be available for work, but the structure of src/netcdf_io/interp_inc.fd/driver.f90 (in the 344-422 line range) is such that it's not available, so the job hangs. I have successfully tested a workaround where the last process (`mype=npes-1`) is used rather than the root process (`mype=0`), but am filing this issue because I'm not very familiar with the code and whether there are reasons to avoid that approach.

**Comment by DavidHuber-NOAA** [comment]
@AlexanderRichert-NOAA Do you have a branch with this fix?  I would like to try it out in #18.

**Comment by AlexanderRichert-NOAA** [comment]
Actually I already pushed the fix last month to develop, just forgot to close the issue.

**Comment by DavidHuber-NOAA** [comment]
Fantastic!  Thanks!
