### ISSUE TITLE
Use EPIC-managed spack-stack installations for non-production machines

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/GSI-utils#18]
The UFS has migrated to spack-stack/1.4.1 and there is work being done to migrate the GSI to the same (NOAA-EMC/GSI#589) on non-production machines (WCOSS2 is still using Intel/19).  The GSI-utils should also be migrated to use spack-stack.  This will involve a few upgrades at once: Intel 18 to 2021+, hdf5/1.10.6 to 1.14.0, and netcdf/4.7.4 to 4.9.2.  It should be noted that during a port to a NESDIS GCP instance, the only compiler available was Intel 2021.  The GSI utilities ran fine at coarser resolutions, but the EnKF recentering utility sometimes failed at ensemble resolution C192.

I am going to try this in one step to bypass #13 (since hpc-stack is minimally supported) and address #15.  My suggested plan for testing is to run 40 cycles in the global workflow at all available resolutions up to C384/C192 and 4 additional cycles at C768/C384 as it is the only application that makes use of this utility suite.

**Comment by RussTreadon-NOAA** [comment]
@DavidHuber-NOAA , does PR #19 close this issue?

**Comment by DavidHuber-NOAA** [comment]
Yes, thanks.  I'll close it now and add the reference to #19.
