### ISSUE TITLE
Update WCOSS2 Modules

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/GSI-utils#20]
The UFS now points to the hpc-stack suite installed in /apps/test/hpc-stack/i-19.1.3.304__m-8.1.12__h-1.14.0__n-4.9.2__p-2.5.10__e-8.4.2.  The GSI-utils modules should be updated to point to the same stack.

**Comment by RussTreadon-NOAA** [comment]
@DavidHuber-NOAA , would updating [`gsiutils_wcoss2.intel.lua`](https://github.com/NOAA-EMC/GSI-utils/blob/develop/modulefiles/gsiutils_wcoss2.intel.lua) to be consistent with GSI [`gsi_wcoss2.intel.lua`](https://github.com/NOAA-EMC/GSI/blob/develop/modulefiles/gsi_wcoss2.intel.lua) be sufficient to close this issue?

**Comment by DavidHuber-NOAA** [comment]
@RussTreadon-NOAA That seems like an important step.  I will add that to my next sprint.

**Comment by RussTreadon-NOAA** [comment]
@DavidHuber-NOAA , if updating [gsiutils_wcoss2.intel.lua](https://github.com/NOAA-EMC/GSI-utils/blob/develop/modulefiles/gsiutils_wcoss2.intel.lua) to be consistent with GSI [gsi_wcoss2.intel.lua](https://github.com/NOAA-EMC/GSI/blob/develop/modulefiles/gsi_wcoss2.intel.lua) is sufficient to close this issue, I can open a PR for this today and request a review from you.  How does this sound?

**Comment by DavidHuber-NOAA** [comment]
Sounds great, thanks @RussTreadon-NOAA!
