### ISSUE TITLE
Remove (some) deprecated utilities.

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/GSI-utils#24]
Specifically:
Radiance_utilities/diag2grads
global_angupdate

These 2 (atleast) have dead links to fortran code from the GSI.  These two are currently not built (or buildable) and therefore are not used (that is an assumption on my part unless someone has a secret way of building them that is not in this repository).

Suggesting to remove them from `develop` (They will always be in the repository history).

@RussTreadon-NOAA @ADCollard @dtkleist 
Please let me know if there are concerns regarding this by Jan 1, 2024.

**Comment by RussTreadon-NOAA** [comment]
@aerorahul , I'm ok with removing the stated apps from GSI-utils.  If anyone wants either app after 1/1/2024, they can recover it from an earlier hash.
